local file = require("csv-table.file")
local fixture = require("support.fixture")

describe("file.columns_from_names", function()
  it("gives a repeated header its occurrence", function()
    local built = file.columns_from_names({ "a", "b", "a" })
    equals(built[1].label, "a[0]")
    equals(built[2].label, "b")
    equals(built[3].label, "a[1]")
  end)

  it("numbers the columns from zero, in file order", function()
    local built = file.columns_from_names({ "a", "b", "a" })
    equals(built[1].column_id, 0)
    equals(built[3].column_id, 2)
  end)
end)

describe("query:display_columns", function()
  it("starts with every column on display", function()
    local view = fixture.duplicated_headers()
    equals(#view:display_columns(), 3)
  end)

  it("leaves out the hidden ones", function()
    local view, source = fixture.duplicated_headers()
    view:hide_column(source[2])

    local display = view:display_columns()
    equals(#display, 2)
    equals(display[2].label, "a[1]")
  end)
end)

describe("query:show_all_columns", function()
  it("puts every column back in file order", function()
    local view, source = fixture.duplicated_headers()
    view:hide_column(source[2])
    view:swap_columns(source[1], 1)

    view:show_all_columns()
    local display = view:display_columns()
    equals(#display, 3)
    equals(display[1].label, "a[0]")
  end)
end)

describe("query:swap_columns", function()
  it("moves a column and keeps its id", function()
    local view, source = fixture.duplicated_headers()
    view:swap_columns(source[1], 1)

    local display = view:display_columns()
    equals(display[1].label, "b")
    equals(display[1].column_id, 1)
  end)

  it("leaves a hidden column between the two where it sits", function()
    local view, source = fixture.duplicated_headers()
    view:hide_column(source[2])
    view:swap_columns(source[1], 1)
    view:swap_columns(source[1], -1)

    equals(view.columns[1].column_id, 0)
    equals(view.columns[2].column_id, 1)
    equals(view.columns[3].column_id, 2)
  end)

  it("refuses to move past the last visible column", function()
    local view, source = fixture.duplicated_headers()
    equals(view:swap_columns(source[3], 1), false)
  end)
end)

describe("query:cut_column and query:paste_columns", function()
  it("takes a column out and puts it back where it was asked for", function()
    local view, source = fixture.duplicated_headers()
    view:cut_column(source[3], false)
    equals(#view:display_columns(), 2)

    view:paste_columns(source[1], true)
    local display = view:display_columns()
    equals(display[1].label, "a[1]")
    equals(display[2].label, "a[0]")
  end)
end)

describe("file.columns", function()
  it("stays in file order however the display is arranged", function()
    local view, source = fixture.duplicated_headers()
    view:swap_columns(source[1], 1)

    equals(view.file.columns[1].label, "a[0]")
    equals(view.file.columns[2].label, "b")
    equals(view.file.columns[3].label, "a[1]")
  end)
end)
