local columns = require("csv-table.columns")
local fixture = require("support.fixture")
local state = require("csv-table.state")

describe("columns.from_names", function()
  it("gives a repeated header its occurrence", function()
    local built = columns.from_names({ "a", "b", "a" })
    equals(built[1].label, "a[0]")
    equals(built[2].label, "b")
    equals(built[3].label, "a[1]")
  end)

  it("numbers the columns from zero, in file order", function()
    local built = columns.from_names({ "a", "b", "a" })
    equals(built[1].column_id, 0)
    equals(built[3].column_id, 2)
  end)
end)

describe("columns.display_columns", function()
  it("starts with every column on display", function()
    local view, _ = fixture.duplicated_headers()
    equals(#columns.display_columns(view), 3)
  end)

  it("leaves out the hidden ones", function()
    local view, source = fixture.duplicated_headers()
    columns.hide(source[2])

    local display = columns.display_columns(view)
    equals(#display, 2)
    equals(display[2].label, "a[1]")
  end)
end)

describe("columns.show_all", function()
  it("puts every column back in file order", function()
    local view, source = fixture.duplicated_headers()
    columns.hide(source[2])
    columns.swap(view, source[1], 1)

    columns.show_all(view)
    local display = columns.display_columns(view)
    equals(#display, 3)
    equals(display[1].label, "a[0]")
  end)
end)

describe("columns.swap", function()
  it("moves a column and keeps its id", function()
    local view, source = fixture.duplicated_headers()
    columns.swap(view, source[1], 1)

    local display = columns.display_columns(view)
    equals(display[1].label, "b")
    equals(display[1].column_id, 1)
  end)

  it("leaves a hidden column between the two where it sits", function()
    local view, source = fixture.duplicated_headers()
    columns.hide(source[2])
    columns.swap(view, source[1], 1)
    columns.swap(view, source[1], -1)

    equals(view.columns[1].column_id, 0)
    equals(view.columns[2].column_id, 1)
    equals(view.columns[3].column_id, 2)
  end)

  it("refuses to move past the last visible column", function()
    local view, source = fixture.duplicated_headers()
    equals(columns.swap(view, source[3], 1), false)
  end)
end)

describe("columns.cut and columns.paste", function()
  it("takes a column out and puts it back where it was asked for", function()
    local view, source = fixture.duplicated_headers()
    columns.cut(view, source[3], false)
    equals(#columns.display_columns(view), 2)

    columns.paste(view, source[1], true)
    local display = columns.display_columns(view)
    equals(display[1].label, "a[1]")
    equals(display[2].label, "a[0]")
  end)
end)

describe("state.source_order", function()
  it("answers in file order however the display is arranged", function()
    local view, source = fixture.duplicated_headers()
    columns.swap(view, source[1], 1)

    local ordered = state.source_order(view)
    equals(ordered[1].label, "a[0]")
    equals(ordered[2].label, "b")
    equals(ordered[3].label, "a[1]")
  end)
end)
